name: Lean Action CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
        - os: ubuntu-latest
          built-bin-name: emcm
          artifact-name: emcm-linux
        - os: macos-latest
          built-bin-name: emcm
          artifact-name: emcm-macos
        - os: windows-latest
          built-bin-name: emcm.exe
          artifact-name: emcm-windows

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        uses: leanprover/lean-action@v1
      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact-name }}
          path: .lake/build/bin/${{ matrix.built-bin-name }}
          if-no-files-found: error

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: github.ref_type == 'tag'
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
    - name: Rename binaries
      run: |
        mv emcm-linux/emcm emcm-linux/emcm-linux
        mv emcm-macos/emcm emcm-macos/emcm-macos
        mv emcm-windows/emcm.exe emcm-windows/emcm-windows.exe
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          emcm-linux/emcm-linux
          emcm-macos/emcm-macos
          emcm-windows/emcm-windows.exe
